.TH "XmCreateButtonBox" "library call"
.SH "NAME"
\fBXmCreateButtonBox\fP \(em The ButtonBox widget creation function
.iX "XmCreateButtonBox"
.iX "creation functions" "XmCreateButtonBox"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ButtonBox\&.h>
\fBWidget \fBXmCreateButtonBox\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\fBArgList \fBarglist\fR\fR,
\fBCardinal \fBargcount\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmCreateButtonBox\fP creates an instance of a ButtonBox
widget and returns the associated widget ID\&.
.IP "\fIparent\fP" 10
Specifies the parent widget ID
.IP "\fIname\fP" 10
Specifies the name of the created widget
.IP "\fIarglist\fP" 10
Specifies the argument list
.IP "\fIargcount\fP" 10
Specifies the number of attribute/value pairs in the argument list
(\fIarglist\fP)
.PP
For a complete definition of ButtonBox and its associated resources, see
\fBXmButtonBox\fP(3)\&.
.SH "RETURN"
.PP
Returns the BulletinBoard widget ID\&.
.SH "RELATED"
.PP
\fBXmButonBox\fP(3)\&.
