.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmMultiListSelectRow" "library call"
.SH "NAME"
\fBXmMultiListSelectRow\fP \(em A MultiList function that selects a row in the list
.iX "XmMultiListSelectRow"
.iX "MultiList functions" "XmMultiListSelectRow"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MultiList\&.h>
\fBvoid \fBXmMultiListSelectRow\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXmString \fBrow\fR\fR,
\fBBoolean \fBnotify\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmMultiListSelectRow\fP highlights the specified row in the MultiList widget\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the MultiList widget from whose list an item is selected\&.
.IP "\fIrow\fP" 10
Specifies the row number (starting from 0) to be selected in the MultiList widget\&.
.IP "\fInotify\fP" 10
Specifies a Boolean value that when TRUE invokes the selection callback
for the current mode\&. From an application interface view, calling this
function with \fInotify\fP True is indistinguishable from a user-initiated
selection action\&.
When \fInotify\fP is FALSE, no callbacks are called\&.
.PP
For a complete definition of MultiList and its associated resources, see
\fBXmMultiList\fP(3)\&.
.SH "RELATED"
.PP
\fBXmMultiList\fP(3)\&.
