.TH "XmMultiListSelectAllItems" "library call"
.SH "NAME"
\fBXmMultiListSelectAllItems\fP \(em an MultiList function that selects all rows of the list
.iX "XmMultiListSelectAllItems"
.iX "MultiList functions" "XmMultiListSelectAllItems"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MultiList\&.h>
\fBvoid \fBXmMultiListSelectAllItems\fP\fR(
\fBWidget \fBwidget\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
Selects all rows of the passed MultiList widget and returns nothing\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the MultiList widget from whose list items is deselected\&.
.PP
For a complete definition of MultiList and its associated resources, see
\fBXmMultiList\fP(3)\&.
.SH "RELATED"
.PP
\fBXmMultiList\fP(3)\&.
