.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmMultiListDeselectRow" "library call"
.SH "NAME"
\fBXmMultiListDeselectRow\fP \(em A MultiList function that deselects a row in the list
.iX "XmMultiListSelectRow"
.iX "MultiList functions" "XmMultiListSelectRow"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MultiList\&.h>
\fBvoid \fBXmMultiListDeselectRow\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXmString \fBrow\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmMultiListDeselectRow\fP unhighlights the specified row in the MultiList widget\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the MultiList widget from whose list an item is deselected\&.
.IP "\fIrow\fP" 10
Specifies the row number (starting from 0) to be deselected in the MultiList widget\&.
.PP
For a complete definition of MultiList and its associated resources, see
\fBXmMultiList\fP(3)\&.
.SH "RELATED"
.PP
\fBXmMultiList\fP(3)\&.
