.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmMultiListSelectItems" "library call"
.SH "NAME"
\fBXmMultiListSelectItems\fP \(em A MultiList function that selects items in the list by matching column entries
.iX "XmMultiListSelectItems"
.iX "List functions" "XmMultiListSelectItems"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MultiList\&.h>
\fBvoid \fBXmMultiListSelectItems\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXmString \fBitem\fR\fR,
\fBint \fBcolumn\fR\fR,
\fBBoolean \fBnotify\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmMultiListSelectItems\fP highlights rows in the list where column
number \fIcolumn\fP matches \fIitem\fP\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the MultiList widget from whose list an item is selected\&.
.IP "\fIitem\fP" 10
Specifies XmString to use as selection key\&.
.IP "\fIcolumn\fP" 10
Specifies a column number (starting from 0) to match, or XmANY_COLUMN for
looking for any column\&.
.IP "\fInotify\fP" 10
Specifies a Boolean value that when TRUE invokes the selection callback
for the current mode\&. From an application interface view, calling this
function with \fInotify\fP True is indistinguishable from a user-initiated
selection action\&.
When \fInotify\fP is FALSE, no callbacks are called\&.
.PP
For a complete definition of MultiList and its associated resources, see
\fBXmMultiList\fP(3)\&.
.SH "RELATED"
.PP
\fBXmMultiList\fP(3) and
\fBXmMultiListGetSelectRows\fP(3)\&.
