.TH "XmMultiListUnselectItem" "library call"
.SH "NAME"
\fBXmMultiListUnselectItem\fP \(em An MultiList function that deselects the specified item of the list
.iX "XmMultiListUnselectItem"
.iX "Extended List functions" "XmMultiListUnselectItem"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MultiList\&.h>
\fBvoid \fBXmMultiListUnselectItem\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXmMultiListRowInfo *\fBrow_info\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmMultiListUnselectItem\fP unselects the row designated by
row_info of the passed MultiList widget\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the MultiList from whose list an item is unselected\&.
.IP "\fIrow_info\fP" 10
Specified the pointer to the row which is to be unselected\&.
.PP
For a complete definition of MultiList and its associated resources,
see \fBXmMultiList\fP(3)\&.
.SH "RELATED"
.PP
\fBXmMultiList\fP(3)\&.
