.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmMultiListDeselectItems" "library call"
.SH "NAME"
\fBXmMultiListDeselectItems\fP \(em A MultiList function that deselects items in the list by matching column entries
.iX "XmMultiListDeselectItems"
.iX "List functions" "XmMultiListDeselectItems"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MultiList\&.h>
\fBvoid \fBXmMultiListDeselectItems\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXmString \fBitem\fR\fR,
\fBint \fBcolumn\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmMultiListDeselectItems\fP unhighlights rows in the list where column
number \fIcolumn\fP matches \fIitem\fP\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the MultiList widget from whose list an item is selected\&.
.IP "\fIitem\fP" 10
Specifies XmString to use as selection key\&.
.IP "\fIcolumn\fP" 10
Specifies a column number (starting from 0) to match, or XmANY_COLUMN for
looking for any column\&.
.PP
For a complete definition of MultiList and its associated resources, see
\fBXmMultiList\fP(3)\&.
.SH "RELATED"
.PP
\fBXmMultiList\fP(3)\&.
