.TH "XmMultiListUnselectAllItems" "library call"
.SH "NAME"
\fBXmMultiListUnselectAllItems\fP \(em an MultiList function that deselects all rows of the list
.iX "XmMultiListUnselectAllItems"
.iX "MultiList functions" "XmMultiListUnselectAllItems"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MultiList\&.h>
\fBvoid \fBXmMultiListUnselectAllItems\fP\fR(
\fBWidget \fBwidget\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
Unselects all rows of the passed MultiList widget and returns nothing\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the MultiList widget from whose list items is deselected\&.
.PP
For a complete definition of MultiList and its associated resources, see
\fBXmMultiList\fP(3)\&.
.SH "RELATED"
.PP
\fBXmMultiList\fP(3)\&.
