.TH "XmMultiListGetSelectedRows" "library call"
.SH "NAME"
\fBXmMultiListGetSelectedRows\fP \(em an MultiList function that returns the rows that currently are selected.
.iX "XmMultiListGetSelectedRows"
.iX "List functions" "XmMultiListGetSelectedRows"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MultiList\&.h>
\fBXmMultiListRowInfo ** \fBXmMultiListGetSelectedRows\fP\fR(
\fBWidget \fBwidget\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
.PP
Use this routine to find the rows that currently are selected in an MultiList widget.
.IP "\fIwidget\fP" 10
Specifies the ID of the MultiList widget\&.
.PP
For a complete definition of MultiList and its associated resources, see
\fBXmMultiList\fP(3)\&.
.SH "RETURN"
.PP
The XmMultiListRowInfo ** returned by this function contains a NULL terminated array of
XmMultiListRowInfo pointers\&. The calling routine is responsible for freeing the
returned pointer with XtFree()\&. The function will return NULL if no elements are selected\&.
.SH "RELATED"
.PP
\fBXmMultiList\fP(3)\&.
