.TH "XmMultiListToggleRow" "library call"
.SH "NAME"
\fBXmMultiListToggleRow\fP \(em An MultiList function that toggles the selection state of a specified row
.iX "XmMultiListToggleRow"
.iX "Extended List functions" "XmMultiListToggleRow"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MultiList\&.h>
\fBvoid \fBXmMultiListToggleRow\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBshort \fBrow\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmMultiListToggleRow\fP toggles the selection state of a row designated by
row argument of the passed MultiList widget\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the MultiList from whose list an item is unselected\&.
.IP "\fIrow\fP" 10
Specified the number of row to toggle\&.
.PP
For a complete definition of MultiList and its associated resources,
see \fBXmMultiList\fP(3)\&.
.SH "RELATED"
.PP
\fBXmMultiList\fP(3)\&.
