.DT
.TH "XmVaCreateScale" "library call"
.SH "NAME"
\fBXmVaCreateScale\fP,
\fBXmVaCreateManagedScale\fP \(em A Scale
widget convenience creation functions\&.
.iX "XmVaCreateToggleScale" "XmVaCreateManagedScale"
.iX "creation functions" "XmVaCreateScale"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Scale\&.h>
.PP
\fBWidget \fBXmVaCreateScale\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedScale\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ToggleButtonGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateScale\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateScale\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of Scale and its associated
resources, see \fBXmScale\fP(3)\&.
.SH "RETURN"
.PP
Returns the Scale widget ID\&.
.SH "RELATED"
.PP
\fBXmScale\fP(3),
\fBXmCreateScale\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
