.DT
.TH "XmVaCreateExt18List" "library call"
.SH "NAME"
\fBXmVaCreateExt18List\fP,
\fBXmVaCreateManagedExt18List\fP \(em A Form
widget convenience creation functions\&.
.iX "XmVaCreateExt18List" "XmVaCreateManagedExt18List"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Ext18List\&.h>
.PP
\fBWidget \fBXmVaCreateExt18List\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedExt18List\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
Ext18List widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateExt18List\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedExt18List\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of Form and its associated
resources, see \fBXmExt18List\fP(3)\&.
.SH "RETURN"
.PP
Returns the Ext18List widget ID\&.
.SH "RELATED"
.PP
\fBXmCreateExt18List\fP(3),
\fBXtCreateManagedWidget\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXmExt18List\fP(3)\&.
