.DT
.TH "XmVaCreateScrollBar" "library call"
.SH "NAME"
\fBXmVaCreateScrollBar\fP,
\fBXmVaCreateManagedScrollBar\fP \(em A ScrollBar
widget convenience creation functions\&.
.iX "XmVaCreateToggleScrollBar" "XmVaCreateManagedScrollBar"
.iX "creation functions" "XmVaCreateScrollBar"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ScrollBar\&.h>
.PP
\fBWidget \fBXmVaCreateScrollBar\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedScrollBar\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ToggleButtonGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateScrollBar\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateScrollBar\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of ScrollBar and its associated
resources, see \fBXmScrollBar\fP(3)\&.
.SH "RETURN"
.PP
Returns the ScrollBar widget ID\&.
.SH "RELATED"
.PP
\fBXmScrollBar\fP(3),
\fBXmCreateScrollBar\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
