.DT
.TH "XmVaCreateText" "library call"
.SH "NAME"
\fBXmVaCreateText\fP,
\fBXmVaCreateManagedText\fP \(em A Text
widget convenience creation functions\&.
.iX "XmVaCreateToggleText" "XmVaCreateManagedText"
.iX "creation functions" "XmVaCreateText"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Text\&.h>
.PP
\fBWidget \fBXmVaCreateText\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedText\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ToggleButtonGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateText\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateText\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of Text and its associated
resources, see \fBXmText\fP(3)\&.
.SH "RETURN"
.PP
Returns the Text widget ID\&.
.SH "RELATED"
.PP
\fBXmText\fP(3),
\fBXmCreateText\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
