.DT
.TH "XmVaCreateSelectionBox" "library call"
.SH "NAME"
\fBXmVaCreateSelectionBox\fP,
\fBXmVaCreateManagedSelectionBox\fP \(em A SelectionBox
widget convenience creation functions\&.
.iX "XmVaCreateToggleSelectionBox" "XmVaCreateManagedSelectionBox"
.iX "creation functions" "XmVaCreateSelectionBox"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/SelectioB\&.h>
.PP
\fBWidget \fBXmVaCreateSelectionBox\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedSelectionBox\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ToggleButtonGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateSelectionBox\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateSelectionBox\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of SelectionBox and its associated
resources, see \fBXmSelectionBox\fP(3)\&.
.SH "RETURN"
.PP
Returns the SelectionBox widget ID\&.
.SH "RELATED"
.PP
\fBXmSelectionBox\fP(3),
\fBXmCreateSelectionBox\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
