.DT
.TH "XmVaCreateForm" "library call"
.SH "NAME"
\fBXmVaCreateForm\fP,
\fBXmVaCreateManagedForm\fP \(em A Form
widget convenience creation functions\&.
.iX "XmVaCreateForm" "XmVaCreateManagedForm"
.iX "creation functions" "XmVaCreateForm"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Form\&.h>
.PP
\fBWidget \fBXmVaCreateForm\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedForm\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
Form widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateForm\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedForm\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of Form and its associated
resources, see \fBXmForm\fP(3)\&.
.SH "RETURN"
.PP
Returns the Form widget ID\&.
.SH "RELATED"
.PP
\fBXmForm\fP(3),
\fBXmCreateForm\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
