.DT
.TH "XmVaCreateContainer" "library call"
.SH "NAME"
\fBXmVaCreateContainer\fP,
\fBXmVaCreateManagedContainer\fP \(em A Container
widget convenience creation functions\&.
.iX "XmVaCreateContainer" "XmVaCreateManagedContainer"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Container\&.h>
.PP
\fBWidget \fBXmVaCreateContainer\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedContainer\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
Container widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateContainer\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreatemanagedContainer\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of Container and its associated
resources, see \fBXmContainer\fP(3)\&.
.SH "RETURN"
.PP
Returns the Container widget ID\&.
.SH "RELATED"
.PP
\fBXmContainer\fP(3),
\fBXmCreateContainer\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
