.DT
.TH "XmVaCreatePanedWindow" "library call"
.SH "NAME"
\fBXmVaCreatePanedWindow\fP,
\fBXmVaCreateManagedPanedWindow\fP \(em A PanedWindow
widget convenience creation functions\&.
.iX "XmVaCreateTogglePanedWindow" "XmVaCreateManagedPanedWindow"
.iX "creation functions" "XmVaCreatePanedWindow"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/PanedW\&.h>
.PP
\fBWidget \fBXmVaCreatePanedWindow\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedPanedWindow\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ToggleButtonGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreatePanedWindow\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreatePanedWindow\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of PanedWindow and its associated
resources, see \fBXmPanedWindow\fP(3)\&.
.SH "RETURN"
.PP
Returns the PanedWindow widget ID\&.
.SH "RELATED"
.PP
\fBXmPanedWindow\fP(3),
\fBXmCreatePanedWindow\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
