.DT
.TH "XmVaCreateIconGadget" "library call"
.SH "NAME"
\fBXmVaCreateIconGadget\fP,
\fBXmVaCreateManagedIconGadget\fP \(em A IconGadget
widget convenience creation functions\&.
.iX "XmVaCreateIconGadget" "XmVaCreateManagedIconGadget"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/IconG\&.h>
.PP
\fBWidget \fBXmVaCreateIconGadget\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedIconGadget\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
IconGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateIconGadget\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedIconGadget\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of IconGadget and its associated
resources, see \fBXmIconGadget\fP(3)\&.
.SH "RETURN"
.PP
Returns the IconGadget widget ID\&.
.SH "RELATED"
.PP
\fBXmIconGadget\fP(3),
\fBXmCreateIconGadget\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
