.DT
.TH "XmVaCreateFrame" "library call"
.SH "NAME"
\fBXmVaCreateFrame\fP,
\fBXmVaCreateManagedFrame\fP \(em A Frame
widget convenience creation functions\&.
.iX "XmVaCreateFrame" "XmVaCreateManagedFrame"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Frame\&.h>
.PP
\fBWidget \fBXmVaCreateFrame\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedFrame\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
Frame widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateFrame\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedFrame\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of Frame and its associated
resources, see \fBXmFrame\fP(3)\&.
.SH "RETURN"
.PP
Returns the Frame widget ID\&.
.SH "RELATED"
.PP
\fBXmFrame\fP(3),
\fBXmCreateFrame\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
