.DT
.TH "XmVaCreatePushButtonGadget" "library call"
.SH "NAME"
\fBXmVaCreatePushButtonGadget\fP,
\fBXmVaCreateManagedPushButtonGadget\fP \(em A PushButtonGadget
widget convenience creation functions\&.
.iX "XmVaCreateTogglePushButtonGadget" "XmVaCreateManagedPushButtonGadget"
.iX "creation functions" "XmVaCreatePushButtonGadget"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/PushBG\&.h>
.PP
\fBWidget \fBXmVaCreatePushButtonGadget\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedPushButtonGadget\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ToggleButtonGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreatePushButtonGadget\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreatePushButtonGadget\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of PushButtonGadget and its associated
resources, see \fBXmPushButtonGadget\fP(3)\&.
.SH "RETURN"
.PP
Returns the PushButtonGadget widget ID\&.
.SH "RELATED"
.PP
\fBXmPushButtonGadget\fP(3),
\fBXmCreatePushButtonGadget\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
