.DT
.TH "XmVaCreateColumn" "library call"
.SH "NAME"
\fBXmVaCreateColumn\fP,
\fBXmVaCreateManagedColumn\fP \(em A Column
widget convenience creation functions\&.
.iX "XmVaCreateColumn" "XmVaCreateManagedColumn"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Column\&.h>
.PP
\fBWidget \fBXmVaCreateColumn\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedColumn\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
Column widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateColumn\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedColumn\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of Column and its associated
resources, see \fBXmColumn\fP(3)\&.
.SH "RETURN"
.PP
Returns the Column widget ID\&.
.SH "RELATED"
.PP
\fBXmColumn\fP(3),
\fBXmCreateColumn\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
