.DT
.TH "XmVaCreateColorSelector" "library call"
.SH "NAME"
\fBXmVaCreateColorSelector\fP,
\fBXmVaCreateManagedColorSelector\fP \(em A ColorSelector
widget convenience creation functions\&.
.iX "XmVaCreateColorSelector" "XmVaCreateManagedColorSelector"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ColorS\&.h>
.PP
\fBWidget \fBXmVaCreateColorSelector\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedColorSelector\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ColorSelector widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateColorSelector\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreatemanagedColorSelector\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of ColorSelector and its associated
resources, see \fBXmColorSelector\fP(3)\&.
.SH "RETURN"
.PP
Returns the ColorSelector widget ID\&.
.SH "RELATED"
.PP
\fBXmColorSelector\fP(3),
\fBXmCreateColorSelector\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
