.DT
.TH "XmVaCreateDrawingArea" "library call"
.SH "NAME"
\fBXmVaCreateDrawingArea\fP,
\fBXmVaCreateManagedDrawingArea\fP \(em A DrawingArea
widget convenience creation functions\&.
.iX "XmVaCreateDrawingArea" "XmVaCreateManagedDrawingArea"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/DrawingA\&.h>
.PP
\fBWidget \fBXmVaCreateDrawingArea\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedDrawingArea\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
DrawingArea widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateDrawingArea\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedDrawingArea\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of DrawingArea and its associated
resources, see \fBXmDrawingArea\fP(3)\&.
.SH "RETURN"
.PP
Returns the DrawingArea widget ID\&.
.SH "RELATED"
.PP
\fBXmDrawingArea\fP(3),
\fBXmCreateDrawingArea\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
