.DT
.TH "XmVaCreateLabel" "library call"
.SH "NAME"
\fBXmVaCreateLabel\fP,
\fBXmVaCreateManagedLabel\fP \(em A Label
widget convenience creation functions\&.
.iX "XmVaCreateLabel" "XmVaCreateManagedLabel"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Label\&.h>
.PP
\fBWidget \fBXmVaCreateLabel\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedLabel\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
Label widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateLabel\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedLabel\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of Label and its associated
resources, see \fBXmLabel\fP(3)\&.
.SH "RETURN"
.PP
Returns the Label widget ID\&.
.SH "RELATED"
.PP
\fBXmLabel\fP(3),
\fBXmCreateLabel\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
