.DT
.TH "XmVaCreateScrolledWindow" "library call"
.SH "NAME"
\fBXmVaCreateScrolledWindow\fP,
\fBXmVaCreateManagedScrolledWindow\fP \(em A ScrolledWindow
widget convenience creation functions\&.
.iX "XmVaCreateToggleScrolledWindow" "XmVaCreateManagedScrolledWindow"
.iX "creation functions" "XmVaCreateScrolledWindow"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ScrolledW\&.h>
.PP
\fBWidget \fBXmVaCreateScrolledWindow\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedScrolledWindow\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ToggleButtonGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateScrolledWindow\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateScrolledWindow\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of ScrolledWindow and its associated
resources, see \fBXmScrolledWindow\fP(3)\&.
.SH "RETURN"
.PP
Returns the ScrolledWindow widget ID\&.
.SH "RELATED"
.PP
\fBXmScrolledWindow\fP(3),
\fBXmCreateScrolledWindow\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
