.DT
.TH "XmVaCreateArrowButton" "library call"
.SH "NAME"
\fBXmVaCreateArrowButton\fP,
\fBXmVaCreateManagedArrowButton\fP \(em A ArrowButton
widget convenience creation functions\&.
.iX "XmVaCreateArrowButton" "XmVaCreateManagedArrowButton"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ArrowB\&.h>
.PP
\fBWidget \fBXmVaCreateArrowButton\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedArrowButton\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ArrowButton widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateArrowButton\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedArrowButton\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of ArrowButton and its associated
resources, see \fBXmArrowButton\fP(3)\&.
.SH "RETURN"
.PP
Returns the ArrowButton widget ID\&.
.SH "RELATED"
.PP
\fBXmArrowButton\fP(3),
\fBXmCreateArrowButton\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
