.DT
.TH "XmVaCreateBulletinBoard" "library call"
.SH "NAME"
\fBXmVaCreateBulletinBoard\fP,
\fBXmVaCreateManagedBulletinBoard\fP \(em A BulletinBoard
widget convenience creation functions\&.
.iX "XmVaCreateBulletinBoard" "XmVaCreateManagedBulletinBoard"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/BulletinB\&.h>
.PP
\fBWidget \fBXmVaCreateBulletinBoard\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedBulletinBoard\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
BulletinBoard widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateBulletinBoard\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedBulletinBoard\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of BulletinBoard and its associated
resources, see \fBXmBulletinBoard\fP(3)\&.
.SH "RETURN"
.PP
Returns the BulletinBoard widget ID\&.
.SH "RELATED"
.PP
\fBXmBulletinBoard\fP(3),
\fBXmCreateBulletinBoard\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
