.DT
.TH "XmVaCreateSpinBox" "library call"
.SH "NAME"
\fBXmVaCreateSpinBox\fP,
\fBXmVaCreateManagedSpinBox\fP \(em A SpinBox
widget convenience creation functions\&.
.iX "XmVaCreateToggleSpinBox" "XmVaCreateManagedSpinBox"
.iX "creation functions" "XmVaCreateSpinBox"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/SpinB\&.h>
.PP
\fBWidget \fBXmVaCreateSpinBox\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedSpinBox\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ToggleButtonGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateSpinBox\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateSpinBox\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of SpinBox and its associated
resources, see \fBXmSpinBox\fP(3)\&.
.SH "RETURN"
.PP
Returns the SpinBox widget ID\&.
.SH "RELATED"
.PP
\fBXmSpinBox\fP(3),
\fBXmCreateSpinBox\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
