.DT
.TH "XmVaCreateCombinationBox2" "library call"
.SH "NAME"
\fBXmVaCreateCombinationBox2\fP,
\fBXmVaCreateManagedCombinationBox2\fP \(em A Form
widget convenience creation functions\&.
.iX "XmVaCreateCombinationBox2" "XmVaCreateManagedCombinationBox2"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ComboBox2\&.h>
.PP
\fBWidget \fBXmVaCreateCombinationBox2\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedCombinationBox2\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
CombinationBox2 widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateCombinationBox2\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedCombinationBox2\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of Form and its associated
resources, see \fBXmCombinationBox2\fP(3)\&.
.SH "RETURN"
.PP
Returns the CombinationBox2 widget ID\&.
.SH "RELATED"
.PP
\fBXmCombinationBox2\fP(3),
\fBXmCreateCombinationBox2\fP(3),
\fBXtCreateManagedWidget\fP(3), and
\fBXtCreateWidget\fP(3)\&.
