.DT
.TH "XmVaCreatePushButton" "library call"
.SH "NAME"
\fBXmVaCreatePushButton\fP,
\fBXmVaCreateManagedPushButton\fP \(em A PushButton
widget convenience creation functions\&.
.iX "XmVaCreateTogglePushButton" "XmVaCreateManagedPushButton"
.iX "creation functions" "XmVaCreatePushButton"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/PushB\&.h>
.PP
\fBWidget \fBXmVaCreatePushButton\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedPushButton\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ToggleButtonGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreatePushButton\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreatePushButton\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of PushButton and its associated
resources, see \fBXmPushButton\fP(3)\&.
.SH "RETURN"
.PP
Returns the PushButton widget ID\&.
.SH "RELATED"
.PP
\fBXmPushButton\fP(3),
\fBXmCreatePushButton\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
