.DT
.TH "XmVaCreateFileSelectionBox" "library call"
.SH "NAME"
\fBXmVaCreateFileSelectionBox\fP,
\fBXmVaCreateManagedFileSelectionBox\fP \(em A FileSelectionBox
widget convenience creation functions\&.
.iX "XmVaCreateFileSelectionBox" "XmVaCreateManagedFileSelectionBox"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/FileSB\&.h>
.PP
\fBWidget \fBXmVaCreateFileSelectionBox\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedFileSelectionBox\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
FileSelectionBox widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateFileSelectionBox\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedFileSelectionBox\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of FileSelectionBox and its associated
resources, see \fBXmFileSelectionBox\fP(3)\&.
.SH "RETURN"
.PP
Returns the FileSelectionBox widget ID\&.
.SH "RELATED"
.PP
\fBXmCreateFileSelectionBox\fP(3),
\fBXtCreateManagedWidget\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXmFileSelectionBox\fP(3)\&.
