.DT
.TH "XmVaCreateLabelGadget" "library call"
.SH "NAME"
\fBXmVaCreateLabelGadget\fP,
\fBXmVaCreateManagedLabelGadget\fP \(em A LabelGadget
widget convenience creation functions\&.
.iX "XmVaCreateLabelGadget" "XmVaCreateManagedLabelGadget"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/LabelG\&.h>
.PP
\fBWidget \fBXmVaCreateLabelGadget\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedLabelGadget\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
LabelGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateLabelGadget\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedLabelGadget\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of LabelGadget and its associated
resources, see \fBXmLabelGadget\fP(3)\&.
.SH "RETURN"
.PP
Returns the LabelGadget widget ID\&.
.SH "RELATED"
.PP
\fBXmLabelGadget\fP(3),
\fBXmCreateLabelGadget\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
