.DT
.TH "XmVaCreateList" "library call"
.SH "NAME"
\fBXmVaCreateList\fP,
\fBXmVaCreateManagedList\fP \(em A List
widget convenience creation functions\&.
.iX "XmVaCreateList" "XmVaCreateManagedList"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/List\&.h>
.PP
\fBWidget \fBXmVaCreateList\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedList\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
List widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateList\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedList\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of List and its associated
resources, see \fBXmList\fP(3)\&.
.SH "RETURN"
.PP
Returns the List widget ID\&.
.SH "RELATED"
.PP
\fBXmList\fP(3),
\fBXmCreateList\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
