.DT
.TH "XmVaCreateNotebook" "library call"
.SH "NAME"
\fBXmVaCreateNotebook\fP,
\fBXmVaCreateManagedNotebook\fP \(em A Notebook
widget convenience creation functions\&.
.iX "XmVaCreateToggleNotebook" "XmVaCreateManagedNotebook"
.iX "creation functions" "XmVaCreateNotebook"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Notebook\&.h>
.PP
\fBWidget \fBXmVaCreateNotebook\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedNotebook\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ToggleButtonGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateNotebook\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateNotebook\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of Notebook and its associated
resources, see \fBXmNotebook\fP(3)\&.
.SH "RETURN"
.PP
Returns the Notebook widget ID\&.
.SH "RELATED"
.PP
\fBXmNotebook\fP(3),
\fBXmCreateNotebook\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
