.DT
.TH "XmVaCreateDrawnButton" "library call"
.SH "NAME"
\fBXmVaCreateDrawnButton\fP,
\fBXmVaCreateManagedDrawnButton\fP \(em A DrawnButton
widget convenience creation functions\&.
.iX "XmVaCreateDrawnButton" "XmVaCreateManagedDrawnButton"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/DrawnB\&.h>
.PP
\fBWidget \fBXmVaCreateDrawnButton\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedDrawnButton\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
DrawnButton widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateDrawnButton\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedDrawnButton\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of DrawnButton and its associated
resources, see \fBXmDrawnButton\fP(3)\&.
.SH "RETURN"
.PP
Returns the DrawnButton widget ID\&.
.SH "RELATED"
.PP
\fBXmDrawnButton\fP(3),
\fBXmCreateDrawnButton\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
