.DT
.TH "XmVaCreateComboBox" "library call"
.SH "NAME"
\fBXmVaCreateComboBox\fP,
\fBXmVaCreateManagedComboBox\fP \(em A ComboBox
widget convenience creation functions\&.
.iX "XmVaCreateComboBox" "XmVaCreateManagedComboBox"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/ComboBox\&.h>
.PP
\fBWidget \fBXmVaCreateComboBox\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedComboBox\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ComboBox widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateComboBox\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedComboBox\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of ComboBox and its associated
resources, see \fBXmComboBox\fP(3)\&.
.SH "RETURN"
.PP
Returns the ComboBox widget ID\&.
.SH "RELATED"
.PP
\fBXmComboBox\fP(3),
\fBXmCreateComboBox\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
