.DT
.TH "XmVaCreateMainWindow" "library call"
.SH "NAME"
\fBXmVaCreateMainWindow\fP,
\fBXmVaCreateManagedMainWindow\fP \(em A MainWindow
widget convenience creation functions\&.
.iX "XmVaCreateMainWindow" "XmVaCreateManagedMainWindow"
.iX "creation functions"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MainW\&.h>
.PP
\fBWidget \fBXmVaCreateMainWindow\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedMainWindow\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
MainWindow widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateMainWindow\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateManagedMainWindow\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of MainWindow and its associated
resources, see \fBXmMainWindow\fP(3)\&.
.SH "RETURN"
.PP
Returns the MainWindow widget ID\&.
.SH "RELATED"
.PP
\fBXmMainWindow\fP(3),
\fBXmCreateMainWindow\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
