.DT
.TH "XmVaCreateTabStack" "library call"
.SH "NAME"
\fBXmVaCreateTabStack\fP,
\fBXmVaCreateManagedTabStack\fP \(em A TabStack
widget convenience creation functions\&.
.iX "XmVaCreateToggleTabStack" "XmVaCreateManagedTabStack"
.iX "creation functions" "XmVaCreateTabStack"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/TabStack\&.h>
.PP
\fBWidget \fBXmVaCreateTabStack\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.PP
\fBWidget \fBXmVaCreateManagedTabStack\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\&.\&.\&.);
.fi
.SH "DESCRIPTION"
.PP
These functions create an instance of a
ToggleButtonGadget widget and returns the associated widget ID\&.
These routines use the ANSI C variable-length argument list (\fIvarargs\fP)
calling convention\&.
.PP
The \fBXmVaCreateTabStack\fP function
is a convenience routine that calls \fBXtCreateWidget\fP\&.
.PP
The \fBXmVaCreateTabStack\fP
function is a convenience routine that calls \fBXtCreateManagedWidget\fP\&.
.PP
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP \fI...\fP
Specifies the variable argument list to override the resource defaults.
.PP
For a complete definition of TabStack and its associated
resources, see \fBXmTabStack\fP(3)\&.
.SH "RETURN"
.PP
Returns the TabStack widget ID\&.
.SH "RELATED"
.PP
\fBXmTabStack\fP(3),
\fBXmCreateTabStack\fP(3),
\fBXtCreateWidget\fP(3), and
\fBXtCreateManagedWidget\fP(3)\&.
