/*
**	This file is automatically generated.  Do not edit it by hand.
**/

/*
 * Enumeration value vectors for each enumeration set
 */


static unsigned short int enum_value_vec1[] =
  {
    75,
    78,
    74,
  };

static unsigned short int enum_value_vec2[] =
  {
    100,
    97,
    98,
    99,
  };

static unsigned short int enum_value_vec3[] =
  {
    88,
    85,
    95,
    90,
    89,
  };

static unsigned short int enum_value_vec4[] =
  {
    96,
    91,
  };

static unsigned short int enum_value_vec5[] =
  {
    93,
    92,
    86,
    94,
    87,
  };

static unsigned short int enum_value_vec6[] =
  {
    104,
    103,
    105,
    109,
    106,
    107,
    108,
  };

static unsigned short int enum_value_vec7[] =
  {
    253,
    116,
  };

static unsigned short int enum_value_vec8[] =
  {
    112,
    111,
  };

static unsigned short int enum_value_vec9[] =
  {
    256,
    113,
    42,
    64,
  };

static unsigned short int enum_value_vec10[] =
  {
    63,
    65,
    1,
  };

static unsigned short int enum_value_vec11[] =
  {
    335,
    337,
    289,
  };

static unsigned short int enum_value_vec12[] =
  {
    42,
    64,
  };

static unsigned short int enum_value_vec13[] =
  {
    294,
    292,
    293,
  };

static unsigned short int enum_value_vec14[] =
  {
    73,
    75,
    72,
    80,
    81,
  };

static unsigned short int enum_value_vec15[] =
  {
    229,
    359,
  };

static unsigned short int enum_value_vec16[] =
  {
    130,
    168,
    169,
  };

static unsigned short int enum_value_vec17[] =
  {
    131,
    132,
  };

static unsigned short int enum_value_vec18[] =
  {
    353,
    342,
    352,
    343,
    350,
    347,
    346,
    354,
    345,
    344,
    348,
    349,
    351,
  };

static unsigned short int enum_value_vec19[] =
  {
    396,
    395,
  };

static unsigned short int enum_value_vec20[] =
  {
    327,
  };

static unsigned short int enum_value_vec21[] =
  {
    140,
    142,
    146,
    149,
    151,
    156,
    157,
  };

static unsigned short int enum_value_vec22[] =
  {
    137,
    397,
    167,
  };

static unsigned short int enum_value_vec23[] =
  {
    158,
    152,
    150,
    162,
    145,
    139,
  };

static unsigned short int enum_value_vec24[] =
  {
    153,
    155,
    162,
    144,
    143,
    147,
    148,
    154,
    160,
    161,
    159,
    141,
  };

static unsigned short int enum_value_vec25[] =
  {
    34,
    33,
    35,
  };

static unsigned short int enum_value_vec26[] =
  {
    4,
    5,
    6,
    3,
  };

static unsigned short int enum_value_vec27[] =
  {
    18,
    17,
    16,
    15,
    14,
  };

static unsigned short int enum_value_vec28[] =
  {
    12,
    11,
    10,
    8,
    9,
  };

static unsigned short int enum_value_vec29[] =
  {
    22,
    27,
    26,
  };

static unsigned short int enum_value_vec30[] =
  {
    32,
    20,
    19,
  };

static unsigned short int enum_value_vec31[] =
  {
    21,
    23,
  };

static unsigned short int enum_value_vec32[] =
  {
    7,
    13,
    2,
  };

static unsigned short int enum_value_vec33[] =
  {
    24,
    25,
  };

static unsigned short int enum_value_vec34[] =
  {
    30,
    31,
    28,
    29,
  };

static unsigned short int enum_value_vec35[] =
  {
    37,
    38,
    39,
    36,
  };

static unsigned short int enum_value_vec36[] =
  {
    331,
    175,
  };

static unsigned short int enum_value_vec37[] =
  {
    330,
    250,
  };

static unsigned short int enum_value_vec38[] =
  {
    221,
    333,
    82,
  };

static unsigned short int enum_value_vec39[] =
  {
    178,
    177,
    176,
  };

static unsigned short int enum_value_vec40[] =
  {
    195,
    193,
    194,
    192,
  };

static unsigned short int enum_value_vec41[] =
  {
    101,
    184,
    185,
    186,
  };

static unsigned short int enum_value_vec42[] =
  {
    189,
    191,
    190,
  };

static unsigned short int enum_value_vec43[] =
  {
    114,
    274,
    135,
    203,
  };

static unsigned short int enum_value_vec44[] =
  {
    221,
    333,
  };

static unsigned short int enum_value_vec45[] =
  {
    220,
    216,
    219,
    215,
    218,
    217,
  };

static unsigned short int enum_value_vec46[] =
  {
    262,
    264,
    266,
    265,
  };

static unsigned short int enum_value_vec47[] =
  {
    62,
    43,
  };

static unsigned short int enum_value_vec48[] =
  {
    280,
    281,
    213,
  };

static unsigned short int enum_value_vec49[] =
  {
    223,
    305,
    384,
    117,
  };

static unsigned short int enum_value_vec50[] =
  {
    174,
    295,
  };

static unsigned short int enum_value_vec51[] =
  {
    341,
    283,
    284,
  };

static unsigned short int enum_value_vec52[] =
  {
    308,
    226,
    307,
    225,
    389,
    388,
    122,
    121,
    387,
    120,
    306,
    224,
    136,
  };

static unsigned short int enum_value_vec53[] =
  {
    267,
    336,
    138,
  };

static unsigned short int enum_value_vec54[] =
  {
    101,
    329,
    166,
    328,
    165,
    257,
  };

static unsigned short int enum_value_vec55[] =
  {
    134,
    401,
    303,
  };

static unsigned short int enum_value_vec56[] =
  {
    101,
    228,
    227,
  };

static unsigned short int enum_value_vec57[] =
  {
    299,
    214,
  };

static unsigned short int enum_value_vec58[] =
  {
    247,
    248,
  };

static unsigned short int enum_value_vec59[] =
  {
    47,
    48,
    52,
    53,
    50,
    51,
    49,
  };

static unsigned short int enum_value_vec60[] =
  {
    54,
    57,
    56,
    51,
    49,
    55,
  };

static unsigned short int enum_value_vec61[] =
  {
    59,
    60,
    61,
    58,
  };

static unsigned short int enum_value_vec62[] =
  {
    253,
    376,
    340,
    172,
  };

static unsigned short int enum_value_vec63[] =
  {
    278,
    230,
    245,
    339,
    279,
  };

static unsigned short int enum_value_vec64[] =
  {
    70,
    300,
  };

static unsigned short int enum_value_vec65[] =
  {
    258,
    402,
    201,
  };

static unsigned short int enum_value_vec66[] =
  {
    269,
    268,
  };

static unsigned short int enum_value_vec67[] =
  {
    129,
    173,
  };

static unsigned short int enum_value_vec68[] =
  {
    259,
    277,
    275,
    276,
  };

static unsigned short int enum_value_vec69[] =
  {
    222,
    183,
  };

static unsigned short int enum_value_vec70[] =
  {
    405,
    263,
  };

static unsigned short int enum_value_vec71[] =
  {
    297,
    298,
  };

static unsigned short int enum_value_vec72[] =
  {
    272,
    270,
    271,
    273,
  };

static unsigned short int enum_value_vec73[] =
  {
    237,
    234,
    235,
    236,
  };

static unsigned short int enum_value_vec74[] =
  {
    304,
    301,
    302,
  };

static unsigned short int enum_value_vec75[] =
  {
    404,
    239,
    242,
    241,
    240,
  };

static unsigned short int enum_value_vec76[] =
  {
    253,
    252,
    251,
    42,
    64,
  };

static unsigned short int enum_value_vec77[] =
  {
    102,
    338,
  };

static unsigned short int enum_value_vec78[] =
  {
    385,
    118,
    386,
    119,
  };

static unsigned short int enum_value_vec79[] =
  {
    202,
    403,
    133,
    243,
    310,
    311,
    260,
    127,
    196,
  };

static unsigned short int enum_value_vec80[] =
  {
    110,
    84,
  };

static unsigned short int enum_value_vec81[] =
  {
    254,
    71,
  };

static unsigned short int enum_value_vec82[] =
  {
    331,
    249,
    175,
    123,
  };

static unsigned short int enum_value_vec83[] =
  {
    231,
    233,
    232,
    390,
    391,
  };

static unsigned short int enum_value_vec84[] =
  {
    329,
    166,
    328,
    165,
    257,
    321,
    323,
    322,
    324,
  };

static unsigned short int enum_value_vec85[] =
  {
    325,
    326,
    321,
    323,
  };

static unsigned short int enum_value_vec86[] =
  {
    170,
    238,
    246,
    42,
    64,
  };

static unsigned short int enum_value_vec87[] =
  {
    40,
    41,
  };

static unsigned short int enum_value_vec88[] =
  {
    253,
    171,
    381,
    309,
  };

static unsigned short int enum_value_vec89[] =
  {
    115,
    188,
    392,
    320,
  };

static unsigned short int enum_value_vec90[] =
  {
    332,
    380,
  };

static unsigned short int enum_value_vec91[] =
  {
    83,
    128,
    182,
  };

static unsigned short int enum_value_vec92[] =
  {
    200,
    199,
    198,
  };

static unsigned short int enum_value_vec93[] =
  {
    253,
    334,
    125,
  };

static unsigned short int enum_value_vec94[] =
  {
    253,
    197,
    124,
  };

static unsigned short int enum_value_vec95[] =
  {
    341,
    261,
  };

static unsigned short int enum_value_vec96[] =
  {
    356,
    357,
  };

static unsigned short int enum_value_vec97[] =
  {
    379,
    378,
  };

static unsigned short int enum_value_vec98[] =
  {
    356,
    357,
    358,
    355,
    136,
  };

static unsigned short int enum_value_vec99[] =
  {
    316,
    317,
    318,
    314,
    313,
    315,
  };

static unsigned short int enum_value_vec100[] =
  {
    212,
    211,
    206,
    207,
    208,
    209,
    210,
    42,
    64,
  };

static unsigned short int enum_value_vec101[] =
  {
    382,
    383,
  };

static unsigned short int enum_value_vec102[] =
  {
    400,
    319,
    205,
    42,
    64,
  };

static unsigned short int enum_value_vec103[] =
  {
    282,
    68,
    66,
    69,
    67,
    204,
    126,
    244,
    296,
    187,
  };

static unsigned short int enum_value_vec104[] =
  {
    399,
    398,
  };

static unsigned short int enum_value_vec105[] =
  {
    73,
    75,
    72,
    77,
    76,
  };

static unsigned short int enum_value_vec106[] =
  {
    312,
    255,
  };

static unsigned short int enum_value_vec107[] =
  {
    401,
    134,
  };

static unsigned short int enum_value_vec108[] =
  {
    74,
    75,
    78,
    79,
  };

static unsigned short int enum_value_vec109[] =
  {
    164,
    163,
  };

static unsigned short int enum_value_vec110[] =
  {
    181,
    179,
    180,
  };

static unsigned short int enum_value_vec111[] =
  {
    291,
    285,
    290,
    286,
    287,
    288,
  };

static unsigned short int enum_value_vec112[] =
  {
    375,
    374,
  };

static unsigned short int enum_value_vec113[] =
  {
    360,
    371,
    372,
  };

static unsigned short int enum_value_vec114[] =
  {
    377,
    368,
    363,
    373,
    362,
  };

static unsigned short int enum_value_vec115[] =
  {
    367,
    364,
    366,
    365,
  };

static unsigned short int enum_value_vec116[] =
  {
    370,
    369,
    361,
  };

static unsigned short int enum_value_vec117[] =
  {
    394,
    393,
    393,
  };

static unsigned short int enum_value_vec118[] =
  {
    46,
    45,
    44,
  };

/*
 * Enumeration set descriptor table
 */
static UilEnumSetDescDef enum_set_table_vec[] =
  {
    {0,NULL},
    {3,enum_value_vec1},
    {4,enum_value_vec2},
    {5,enum_value_vec3},
    {2,enum_value_vec4},
    {5,enum_value_vec5},
    {7,enum_value_vec6},
    {2,enum_value_vec7},
    {2,enum_value_vec8},
    {4,enum_value_vec9},
    {3,enum_value_vec10},
    {3,enum_value_vec11},
    {2,enum_value_vec12},
    {3,enum_value_vec13},
    {5,enum_value_vec14},
    {2,enum_value_vec15},
    {3,enum_value_vec16},
    {2,enum_value_vec17},
    {13,enum_value_vec18},
    {2,enum_value_vec19},
    {1,enum_value_vec20},
    {7,enum_value_vec21},
    {3,enum_value_vec22},
    {6,enum_value_vec23},
    {12,enum_value_vec24},
    {3,enum_value_vec25},
    {4,enum_value_vec26},
    {5,enum_value_vec27},
    {5,enum_value_vec28},
    {3,enum_value_vec29},
    {3,enum_value_vec30},
    {2,enum_value_vec31},
    {3,enum_value_vec32},
    {2,enum_value_vec33},
    {4,enum_value_vec34},
    {4,enum_value_vec35},
    {2,enum_value_vec36},
    {2,enum_value_vec37},
    {3,enum_value_vec38},
    {3,enum_value_vec39},
    {4,enum_value_vec40},
    {4,enum_value_vec41},
    {3,enum_value_vec42},
    {4,enum_value_vec43},
    {2,enum_value_vec44},
    {6,enum_value_vec45},
    {4,enum_value_vec46},
    {2,enum_value_vec47},
    {3,enum_value_vec48},
    {4,enum_value_vec49},
    {2,enum_value_vec50},
    {3,enum_value_vec51},
    {13,enum_value_vec52},
    {3,enum_value_vec53},
    {6,enum_value_vec54},
    {3,enum_value_vec55},
    {3,enum_value_vec56},
    {2,enum_value_vec57},
    {2,enum_value_vec58},
    {7,enum_value_vec59},
    {6,enum_value_vec60},
    {4,enum_value_vec61},
    {4,enum_value_vec62},
    {5,enum_value_vec63},
    {2,enum_value_vec64},
    {3,enum_value_vec65},
    {2,enum_value_vec66},
    {2,enum_value_vec67},
    {4,enum_value_vec68},
    {2,enum_value_vec69},
    {2,enum_value_vec70},
    {2,enum_value_vec71},
    {4,enum_value_vec72},
    {4,enum_value_vec73},
    {3,enum_value_vec74},
    {5,enum_value_vec75},
    {5,enum_value_vec76},
    {2,enum_value_vec77},
    {4,enum_value_vec78},
    {9,enum_value_vec79},
    {2,enum_value_vec80},
    {2,enum_value_vec81},
    {4,enum_value_vec82},
    {5,enum_value_vec83},
    {9,enum_value_vec84},
    {4,enum_value_vec85},
    {5,enum_value_vec86},
    {2,enum_value_vec87},
    {4,enum_value_vec88},
    {4,enum_value_vec89},
    {2,enum_value_vec90},
    {3,enum_value_vec91},
    {3,enum_value_vec92},
    {3,enum_value_vec93},
    {3,enum_value_vec94},
    {2,enum_value_vec95},
    {2,enum_value_vec96},
    {2,enum_value_vec97},
    {5,enum_value_vec98},
    {6,enum_value_vec99},
    {9,enum_value_vec100},
    {2,enum_value_vec101},
    {5,enum_value_vec102},
    {10,enum_value_vec103},
    {2,enum_value_vec104},
    {5,enum_value_vec105},
    {2,enum_value_vec106},
    {2,enum_value_vec107},
    {4,enum_value_vec108},
    {2,enum_value_vec109},
    {3,enum_value_vec110},
    {6,enum_value_vec111},
    {2,enum_value_vec112},
    {3,enum_value_vec113},
    {5,enum_value_vec114},
    {4,enum_value_vec115},
    {3,enum_value_vec116},
    {3,enum_value_vec117},
    {3,enum_value_vec118},
  };
externaldef(uil_sym_glbl) UilEnumSetDescDef *enum_set_table =
		enum_set_table_vec;
/*
 * Enumeration set table, accessed by sym_k_..._arg code. Each non-zero entry
 * is the sym_k_..._enumset code for the argument's enumeration set.
 */
static unsigned short int argument_enumset_table_vec[] =
  {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    25,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    26,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    27,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    28,
    0,
    0,
    0,
    0,
    0,
    29,
    0,
    33,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    32,
    0,
    0,
    0,
    0,
    0,
    0,
    34,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    35,
    0,
    0,
    0,
    0,
    0,
    49,
    0,
    87,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    3,
    4,
    5,
    0,
    0,
    7,
    0,
    8,
    0,
    0,
    0,
    9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    11,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    6,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    13,
    42,
    14,
    0,
    0,
    0,
    0,
    15,
    0,
    0,
    0,
    0,
    16,
    0,
    0,
    0,
    17,
    117,
    0,
    19,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    5,
    0,
    0,
    21,
    0,
    108,
    0,
    0,
    110,
    0,
    0,
    22,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    23,
    0,
    24,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    109,
    0,
    37,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    108,
    0,
    0,
    0,
    0,
    0,
    0,
    105,
    38,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    39,
    0,
    0,
    40,
    110,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    41,
    0,
    0,
    0,
    0,
    42,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    45,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    100,
    0,
    46,
    0,
    0,
    0,
    47,
    0,
    0,
    0,
    0,
    48,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    50,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    51,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    52,
    53,
    6,
    0,
    0,
    0,
    0,
    0,
    0,
    118,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    55,
    0,
    0,
    0,
    56,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    57,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    58,
    0,
    59,
    60,
    61,
    0,
    62,
    0,
    0,
    0,
    0,
    0,
    0,
    43,
    63,
    0,
    0,
    0,
    0,
    64,
    0,
    0,
    0,
    0,
    65,
    0,
    66,
    0,
    0,
    20,
    67,
    0,
    68,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    111,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    69,
    70,
    71,
    0,
    0,
    72,
    73,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    74,
    0,
    0,
    0,
    6,
    0,
    0,
    0,
    75,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    77,
    78,
    0,
    0,
    0,
    0,
    79,
    0,
    0,
    80,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    81,
    82,
    83,
    0,
    0,
    84,
    102,
    0,
    85,
    103,
    86,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    76,
    0,
    0,
    88,
    0,
    0,
    89,
    90,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    91,
    92,
    93,
    94,
    95,
    0,
    0,
    54,
    96,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    112,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    113,
    0,
    114,
    111,
    0,
    0,
    115,
    96,
    116,
    0,
    97,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    101,
    0,
    0,
    0,
    0,
    6,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    54,
    0,
    103,
    104,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    44,
    0,
    0,
    0,
    106,
    107,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    18,
  };
externaldef(uil_sym_glbl) unsigned short int *argument_enumset_table =
		argument_enumset_table_vec;
/*
 * Enumeration value table, accessed by sym_k_..._enumval code. Each entry is
 * the actual value associated with the code.
 */
static int enumval_values_table_vec[] =
  {
  0,
  Always,
  DtHELP_AS_NEEDED_SCROLLBARS,
  DtHELP_EXECUTE_ALL,
  DtHELP_EXECUTE_NONE,
  DtHELP_EXECUTE_QUERY_ALL,
  DtHELP_EXECUTE_QUERY_UNALIASED,
  DtHELP_NO_SCROLLBARS,
  DtHELP_PAPERSIZE_A4,
  DtHELP_PAPERSIZE_B5,
  DtHELP_PAPERSIZE_EXECUTIVE,
  DtHELP_PAPERSIZE_LEGAL,
  DtHELP_PAPERSIZE_LETTER,
  DtHELP_STATIC_SCROLLBARS,
  DtHELP_TYPE_DYNAMIC_STRING,
  DtHELP_TYPE_FILE,
  DtHELP_TYPE_MAN_PAGE,
  DtHELP_TYPE_STRING,
  DtHELP_TYPE_TOPIC,
  DtLONG_NAME,
  DtMEDIUM_NAME,
  DtPRINT_CLOSE_CONNECTION,
  DtPRINT_NO_DESTINATION,
  DtPRINT_RELEASE_CONNECTION,
  DtPRINT_SETUP_PLAIN,
  DtPRINT_SETUP_XP,
  DtPRINT_TO_FILE,
  DtPRINT_TO_PRINTER,
  DtSHADOW_ETCHED_IN,
  DtSHADOW_ETCHED_OUT,
  DtSHADOW_IN,
  DtSHADOW_OUT,
  DtSHORT_NAME,
  DtTERM_CHAR_CURSOR_BAR,
  DtTERM_CHAR_CURSOR_BOX,
  DtTERM_CHAR_CURSOR_INVISIBLE,
  DtWORK_AREA_BOTTOM,
  DtWORK_AREA_NONE,
  DtWORK_AREA_TOP,
  DtWORK_AREA_TOP_AND_BOTTOM,
  ExmSHAPE_OVAL,
  ExmSHAPE_RECTANGLE,
  FALSE,
  IconicState,
  LineDoubleDash,
  LineOnOffDash,
  LineSolid,
  MWM_DECOR_ALL,
  MWM_DECOR_BORDER,
  MWM_DECOR_MAXIMIZE,
  MWM_DECOR_MENU,
  MWM_DECOR_MINIMIZE,
  MWM_DECOR_RESIZEH,
  MWM_DECOR_TITLE,
  MWM_FUNC_ALL,
  MWM_FUNC_CLOSE,
  MWM_FUNC_MOVE,
  MWM_FUNC_RESIZE,
  MWM_INPUT_FULL_APPLICATION_MODAL,
  MWM_INPUT_MODELESS,
  MWM_INPUT_PRIMARY_APPLICATION_MODAL,
  MWM_INPUT_SYSTEM_MODAL,
  NormalState,
  NotUseful,
  TRUE,
  WhenMapped,
  Xm1000TH_INCHES,
  Xm100TH_FONT_UNITS,
  Xm100TH_MILLIMETERS,
  Xm100TH_POINTS,
  XmABSOLUTE,
  XmADD_MODE,
  XmALIGNMENT_BASELINE_BOTTOM,
  XmALIGNMENT_BASELINE_TOP,
  XmALIGNMENT_BEGINNING,
  XmALIGNMENT_CENTER,
  XmALIGNMENT_CONTENTS_BOTTOM,
  XmALIGNMENT_CONTENTS_TOP,
  XmALIGNMENT_END,
  XmALIGNMENT_UNSPECIFIED,
  XmALIGNMENT_WIDGET_BOTTOM,
  XmALIGNMENT_WIDGET_TOP,
  XmANY_ICON,
  XmAPPEND,
  XmAPPLICATION_DEFINED,
  XmARROWS_BEGINNING,
  XmARROWS_DECREMENT_SENSITIVE,
  XmARROWS_DEFAULT_SENSITIVITY,
  XmARROWS_END,
  XmARROWS_FLAT_BEGINNING,
  XmARROWS_FLAT_END,
  XmARROWS_HORIZONTAL,
  XmARROWS_INCREMENT_SENSITIVE,
  XmARROWS_INSENSITIVE,
  XmARROWS_SENSITIVE,
  XmARROWS_SPLIT,
  XmARROWS_VERTICAL,
  XmARROW_DOWN,
  XmARROW_LEFT,
  XmARROW_RIGHT,
  XmARROW_UP,
  XmAS_IS,
  XmAS_NEEDED,
  XmATTACH_FORM,
  XmATTACH_NONE,
  XmATTACH_OPPOSITE_FORM,
  XmATTACH_OPPOSITE_WIDGET,
  XmATTACH_POSITION,
  XmATTACH_SELF,
  XmATTACH_WIDGET,
  XmAUTOMATIC,
  XmAUTO_DRAG_DISABLED,
  XmAUTO_DRAG_ENABLED,
  XmAUTO_SELECT,
  XmAlwaysOpen,
  XmBACKGROUND_COLOR,
  XmBELL,
  XmBOTTOM,
  XmBOTTOM_LEFT,
  XmBOTTOM_RIGHT,
  XmBOTTOM_TO_TOP,
  XmBOTTOM_TO_TOP_LEFT_TO_RIGHT,
  XmBOTTOM_TO_TOP_RIGHT_TO_LEFT,
  XmBROWSE_SELECT,
  XmCELLS,
  XmCENTER,
  XmCENTIMETERS,
  XmCLIP_WINDOW,
  XmCLOSEST,
  XmCOLLAPSED,
  XmCOMBO_BOX,
  XmCOMMAND_ABOVE_WORKSPACE,
  XmCOMMAND_BELOW_WORKSPACE,
  XmCOMMAND_WINDOW,
  XmCONSTANT,
  XmClosed,
  XmDEFAULT_DIRECTION,
  XmDESTROY,
  XmDETAIL,
  XmDIALOG_APPLICATION_MODAL,
  XmDIALOG_CANCEL_BUTTON,
  XmDIALOG_COMMAND,
  XmDIALOG_DEFAULT_BUTTON,
  XmDIALOG_ERROR,
  XmDIALOG_FILE_SELECTION,
  XmDIALOG_FULL_APPLICATION_MODAL,
  XmDIALOG_HELP_BUTTON,
  XmDIALOG_INFORMATION,
  XmDIALOG_MESSAGE,
  XmDIALOG_MESSAGE_LABEL,
  XmDIALOG_MODELESS,
  XmDIALOG_OK_BUTTON,
  XmDIALOG_PRIMARY_APPLICATION_MODAL,
  XmDIALOG_PROMPT,
  XmDIALOG_QUESTION,
  XmDIALOG_SELECTION,
  XmDIALOG_SEPARATOR,
  XmDIALOG_SYMBOL_LABEL,
  XmDIALOG_SYSTEM_MODAL,
  XmDIALOG_TEMPLATE,
  XmDIALOG_WARNING,
  XmDIALOG_WORKING,
  XmDIALOG_WORK_AREA,
  XmDISTRIBUTE_SPREAD,
  XmDISTRIBUTE_TIGHT,
  XmDOUBLE_DASHED_LINE,
  XmDOUBLE_LINE,
  XmDO_NOTHING,
  XmDROP_DOWN_COMBO_BOX,
  XmDROP_DOWN_LIST,
  XmEACH_SIDE,
  XmETCHED_LINE,
  XmEXCLUSIVE_TAB_GROUP,
  XmEXPANDED,
  XmEXPLICIT,
  XmEXTENDED_SELECT,
  XmFILE_ANY_TYPE,
  XmFILE_DIRECTORY,
  XmFILE_REGULAR,
  XmFILL_FLUSH,
  XmFILL_RAGGED,
  XmFILL_UNSPECIFIED,
  XmFIRST_FIT,
  XmFIRST_POSITION,
  XmFONT_IS_FONT,
  XmFONT_IS_FONTSET,
  XmFONT_IS_XFT,
  XmFONT_UNITS,
  XmFOREGROUND_COLOR,
  XmFRAME_GENERIC_CHILD,
  XmFRAME_TITLE_CHILD,
  XmFRAME_WORKAREA_CHILD,
  XmFillAll,
  XmFillMajor,
  XmFillMinor,
  XmFillNone,
  XmGENERIC_CHILD,
  XmGRID,
  XmGROW_BALANCED,
  XmGROW_MAJOR,
  XmGROW_MINOR,
  XmHORIZONTAL,
  XmHOR_SCROLLBAR,
  XmHidden,
  XmINCHES,
  XmINDETERMINATE,
  XmINDICATOR_BOX,
  XmINDICATOR_CHECK,
  XmINDICATOR_CHECK_BOX,
  XmINDICATOR_CROSS,
  XmINDICATOR_CROSS_BOX,
  XmINDICATOR_FILL,
  XmINDICATOR_NONE,
  XmINHERIT_POLICY,
  XmINVALID_MATCH_BEHAVIOR,
  XmIconBottom,
  XmIconLeft,
  XmIconNone,
  XmIconOnly,
  XmIconRight,
  XmIconTop,
  XmLARGE_ICON,
  XmLAST_POSITION,
  XmLEFT,
  XmLEFT_TO_RIGHT,
  XmLEFT_TO_RIGHT_BOTTOM_TO_TOP,
  XmLEFT_TO_RIGHT_TOP_TO_BOTTOM,
  XmLOAD_DEFERRED,
  XmLOAD_IMMEDIATE,
  XmListMode,
  XmMAJOR_TAB,
  XmMARQUEE,
  XmMARQUEE_EXTEND_BOTH,
  XmMARQUEE_EXTEND_START,
  XmMAX_ON_BOTTOM,
  XmMAX_ON_LEFT,
  XmMAX_ON_RIGHT,
  XmMAX_ON_TOP,
  XmMAX_SIDE,
  XmMENU_BAR,
  XmMENU_OPTION,
  XmMENU_POPUP,
  XmMENU_PULLDOWN,
  XmMESSAGE_WINDOW,
  XmMILLIMETERS,
  XmMINOR_TAB,
  XmMIN_SIDE,
  XmMULTICLICK_DISCARD,
  XmMULTICLICK_KEEP,
  XmMULTIPLE_SELECT,
  XmMULTI_LINE_EDIT,
  XmNEAR_BORDER,
  XmNEAR_SLIDER,
  XmNONE,
  XmNORMAL_MODE,
  XmNOT_SELECTED,
  XmNO_AUTO_SELECT,
  XmNO_LINE,
  XmNO_ORIENTATION,
  XmNO_PACKING,
  XmNO_SCROLL,
  XmNUMERIC,
  XmN_OF_MANY,
  XmONE_BASED,
  XmONE_OF_MANY,
  XmONE_OF_MANY_DIAMOND,
  XmONE_OF_MANY_ROUND,
  XmOUTLINE,
  XmOUTLINE_BUTTON_ABSENT,
  XmOUTLINE_BUTTON_PRESENT,
  XmOWN_ALWAYS,
  XmOWN_MULTIPLE,
  XmOWN_NEVER,
  XmOWN_POSSIBLE_MULTIPLE,
  XmOpen,
  XmPACK_COLUMN,
  XmPACK_NONE,
  XmPACK_TIGHT,
  XmPAGE,
  XmPAGE_SCROLLER,
  XmPER_SHELL,
  XmPER_WIDGET,
  XmPIXELS,
  XmPIXMAP,
  XmPIXMAP_AND_STRING,
  XmPIXMAP_BOTTOM,
  XmPIXMAP_LEFT,
  XmPIXMAP_NONE,
  XmPIXMAP_ONLY,
  XmPIXMAP_OVERLAP_ONLY,
  XmPIXMAP_RIGHT,
  XmPIXMAP_TOP,
  XmPLACE_ABOVE_SELECTION,
  XmPLACE_BELOW_SELECTION,
  XmPLACE_TOP,
  XmPOINTER,
  XmPOINTS,
  XmPOSITION_INDEX,
  XmPOSITION_VALUE,
  XmQUICK_NAVIGATE,
  XmRELATIVE,
  XmRESIZE_ANY,
  XmRESIZE_GROW,
  XmRESIZE_IF_POSSIBLE,
  XmRESIZE_NONE,
  XmRIGHT,
  XmRIGHT_TO_LEFT,
  XmRIGHT_TO_LEFT_BOTTOM_TO_TOP,
  XmRIGHT_TO_LEFT_TOP_TO_BOTTOM,
  XmROUND_MARK,
  XmSCROLL_HOR,
  XmSCROLL_VERT,
  XmSELECTED,
  XmSELECT_ALL,
  XmSELECT_LINE,
  XmSELECT_PARAGRAPH,
  XmSELECT_POSITION,
  XmSELECT_WHITESPACE,
  XmSELECT_WORD,
  XmSET,
  XmSHADOWED_BACKGROUND,
  XmSHADOW_ETCHED_IN,
  XmSHADOW_ETCHED_IN_DASH,
  XmSHADOW_ETCHED_OUT,
  XmSHADOW_ETCHED_OUT_DASH,
  XmSHADOW_IN,
  XmSHADOW_OUT,
  XmSINGLE,
  XmSINGLE_DASHED_LINE,
  XmSINGLE_LINE,
  XmSINGLE_LINE_EDIT,
  XmSINGLE_SELECT,
  XmSLIDER,
  XmSMALL_ICON,
  XmSNAP_TO_GRID,
  XmSOLID,
  XmSPATIAL,
  XmSPIRAL,
  XmSTATIC,
  XmSTATUS_AREA,
  XmSTICKY_TAB_GROUP,
  XmSTRING,
  XmSTRING_COMPONENT_CHARSET,
  XmSTRING_COMPONENT_DIRECTION,
  XmSTRING_COMPONENT_LAYOUT_POP,
  XmSTRING_COMPONENT_LAYOUT_PUSH,
  XmSTRING_COMPONENT_LOCALE,
  XmSTRING_COMPONENT_LOCALE_TEXT,
  XmSTRING_COMPONENT_RENDITION_BEGIN,
  XmSTRING_COMPONENT_RENDITION_END,
  XmSTRING_COMPONENT_SEPARATOR,
  XmSTRING_COMPONENT_TAB,
  XmSTRING_COMPONENT_TEXT,
  XmSTRING_COMPONENT_UNKNOWN,
  XmSTRING_COMPONENT_WIDECHAR_TEXT,
  XmSTRING_DIRECTION_DEFAULT,
  XmSTRING_DIRECTION_L_TO_R,
  XmSTRING_DIRECTION_R_TO_L,
  XmSTRING_DIRECTION_UNSET,
  XmScaleMode,
  XmTABS_BASIC,
  XmTABS_BEVELED,
  XmTABS_BOTTOM_TO_TOP,
  XmTABS_LEFT_TO_RIGHT,
  XmTABS_ON_BOTTOM,
  XmTABS_ON_LEFT,
  XmTABS_ON_RIGHT,
  XmTABS_ON_TOP,
  XmTABS_RIGHT_TO_LEFT,
  XmTABS_ROUNDED,
  XmTABS_SQUARED,
  XmTABS_STACKED,
  XmTABS_STACKED_STATIC,
  XmTABS_TOP_TO_BOTTOM,
  XmTAB_EDGE_BOTTOM_RIGHT,
  XmTAB_EDGE_TOP_LEFT,
  XmTAB_GROUP,
  XmTAB_ORIENTATION_DYNAMIC,
  XmTEAR_OFF_DISABLED,
  XmTEAR_OFF_ENABLED,
  XmTHERMOMETER,
  XmTHUMB_MARK,
  XmTOGGLE_BOOLEAN,
  XmTOGGLE_INDETERMINATE,
  XmTOP,
  XmTOP_LEFT,
  XmTOP_RIGHT,
  XmTOP_TO_BOTTOM,
  XmTOP_TO_BOTTOM_LEFT_TO_RIGHT,
  XmTOP_TO_BOTTOM_RIGHT_TO_LEFT,
  XmTOUCH_ONLY,
  XmTOUCH_OVER,
  XmTROUGH_COLOR,
  XmTreeCompressLeaves,
  XmTreeCompressNone,
  XmTreeDirect,
  XmTreeLadder,
  XmUNMAP,
  XmUNPOST,
  XmUNPOST_AND_REPLAY,
  XmUNSET,
  XmVARIABLE,
  XmVERTICAL,
  XmVERT_SCROLLBAR,
  XmWORK_AREA,
  XmZERO_BASED,
  };
externaldef(uil_sym_glbl) int *enumval_values_table =
		enumval_values_table_vec;
