/* $XConsortium: MrmMsgI.h /main/2 1996/08/19 12:09:55 pascale $ */
/*
 *
 *  @OPENGROUP_COPYRIGHT@
 *  COPYRIGHT NOTICE
 *  Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
 *  Copyright (c) 1996, 1997, 1998, 1999, 2000 The Open Group
 *  ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
 *  the full copyright text.
 *  
 *  This software is subject to an open license. It may only be
 *  used on, with or for operating systems which are themselves open
 *  source systems. You must contact The Open Group for a license
 *  allowing distribution and sublicensing of this software on, with,
 *  or for operating systems which are not Open Source programs.
 *  
 *  See http://www.opengroup.org/openmotif/license for full
 *  details of the license agreement. Any use, reproduction, or
 *  distribution of the program constitutes recipient's acceptance of
 *  this agreement.
 *  
 *  EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, THE PROGRAM IS
 *  PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY
 *  WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY
 *  OR FITNESS FOR A PARTICULAR PURPOSE
 *  
 *  EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, NEITHER RECIPIENT
 *  NOR ANY CONTRIBUTORS SHALL HAVE ANY LIABILITY FOR ANY DIRECT,
 *  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 *  DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED
 *  AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OR DISTRIBUTION OF THE PROGRAM OR THE
 *  EXERCISE OF ANY RIGHTS GRANTED HEREUNDER, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGES.
 */
/*
 * (c) Copyright 1996 Digital Equipment Corporation.
 * (c) Copyright 1996 Hewlett-Packard Company.
 * (c) Copyright 1996 International Business Machines Corp.
 * (c) Copyright 1996 Sun Microsystems, Inc.
 * (c) Copyright 1996 Novell, Inc. 
 * (c) Copyright 1996 FUJITSU LIMITED.
 * (c) Copyright 1996 Hitachi.
 */
/* This file is automatically generated. */
/* Do not edit. */

#ifndef NO_MESSAGE_CATALOG

#include <nl_types.h>
#include "MrmMsgCatI.h"

externalref nl_catd Mrm_catd;

#define _MrmCatgets(catd, set_num, msg_num, def_str) \
        catgets(catd, set_num, msg_num, def_str)

#else

#define _MrmCatgets(catd, set_num, msg_num, def_str)   def_str

#endif /* NO_MESSAGE_CATALOG */

#define _MrmMMsg_0000                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0000, _MrmMsg_0000)
#define _MrmMMsg_0001                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0001, _MrmMsg_0001)
#define _MrmMMsg_0002                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0002, _MrmMsg_0002)
#define _MrmMMsg_0003                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0003, _MrmMsg_0003)
#define _MrmMMsg_0004                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0004, _MrmMsg_0004)
#define _MrmMMsg_0005                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0005, _MrmMsg_0005)
#define _MrmMMsg_0006                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0006, _MrmMsg_0006)
#define _MrmMMsg_0007                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0007, _MrmMsg_0007)
#define _MrmMMsg_0008                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0008, _MrmMsg_0008)
#define _MrmMMsg_0009                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0009, _MrmMsg_0009)
#define _MrmMMsg_0010                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0010, _MrmMsg_0010)
#define _MrmMMsg_0011                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0011, _MrmMsg_0011)
#define _MrmMMsg_0012                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0012, _MrmMsg_0012)
#define _MrmMMsg_0013                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0013, _MrmMsg_0013)
#define _MrmMMsg_0014                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0014, _MrmMsg_0014)
#define _MrmMMsg_0015                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0015, _MrmMsg_0015)
#define _MrmMMsg_0016                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0016, _MrmMsg_0016)
#define _MrmMMsg_0017                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0017, _MrmMsg_0017)
#define _MrmMMsg_0018                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0018, _MrmMsg_0018)
#define _MrmMMsg_0019                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0019, _MrmMsg_0019)
#define _MrmMMsg_0020                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0020, _MrmMsg_0020)
#define _MrmMMsg_0021                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0021, _MrmMsg_0021)
#define _MrmMMsg_0022                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0022, _MrmMsg_0022)
#define _MrmMMsg_0023                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0023, _MrmMsg_0023)
#define _MrmMMsg_0024                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0024, _MrmMsg_0024)
#define _MrmMMsg_0025                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0025, _MrmMsg_0025)
#define _MrmMMsg_0026                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0026, _MrmMsg_0026)
#define _MrmMMsg_0027                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0027, _MrmMsg_0027)
#define _MrmMMsg_0028                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0028, _MrmMsg_0028)
#define _MrmMMsg_0029                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0029, _MrmMsg_0029)
#define _MrmMMsg_0030                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0030, _MrmMsg_0030)
#define _MrmMMsg_0031                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0031, _MrmMsg_0031)
#define _MrmMMsg_0032                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0032, _MrmMsg_0032)
#define _MrmMMsg_0033                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0033, _MrmMsg_0033)
#define _MrmMMsg_0034                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0034, _MrmMsg_0034)
#define _MrmMMsg_0035                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0035, _MrmMsg_0035)
#define _MrmMMsg_0036                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0036, _MrmMsg_0036)
#define _MrmMMsg_0037                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0037, _MrmMsg_0037)
#define _MrmMMsg_0038                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0038, _MrmMsg_0038)
#define _MrmMMsg_0039                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0039, _MrmMsg_0039)
#define _MrmMMsg_0040                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0040, _MrmMsg_0040)
#define _MrmMMsg_0041                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0041, _MrmMsg_0041)
#define _MrmMMsg_0042                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0042, _MrmMsg_0042)
#define _MrmMMsg_0043                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0043, _MrmMsg_0043)
#define _MrmMMsg_0044                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0044, _MrmMsg_0044)
#define _MrmMMsg_0045                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0045, _MrmMsg_0045)
#define _MrmMMsg_0046                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0046, _MrmMsg_0046)
#define _MrmMMsg_0047                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0047, _MrmMsg_0047)
#define _MrmMMsg_0048                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0048, _MrmMsg_0048)
#define _MrmMMsg_0049                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0049, _MrmMsg_0049)
#define _MrmMMsg_0050                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0050, _MrmMsg_0050)
#define _MrmMMsg_0051                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0051, _MrmMsg_0051)
#define _MrmMMsg_0052                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0052, _MrmMsg_0052)
#define _MrmMMsg_0053                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0053, _MrmMsg_0053)
#define _MrmMMsg_0054                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0054, _MrmMsg_0054)
#define _MrmMMsg_0055                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0055, _MrmMsg_0055)
#define _MrmMMsg_0056                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0056, _MrmMsg_0056)
#define _MrmMMsg_0057                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0057, _MrmMsg_0057)
#define _MrmMMsg_0058                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0058, _MrmMsg_0058)
#define _MrmMMsg_0059                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0059, _MrmMsg_0059)
#define _MrmMMsg_0060                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0060, _MrmMsg_0060)
#define _MrmMMsg_0061                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0061, _MrmMsg_0061)
#define _MrmMMsg_0062                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0062, _MrmMsg_0062)
#define _MrmMMsg_0063                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0063, _MrmMsg_0063)
#define _MrmMMsg_0064                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0064, _MrmMsg_0064)
#define _MrmMMsg_0065                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0065, _MrmMsg_0065)
#define _MrmMMsg_0066                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0066, _MrmMsg_0066)
#define _MrmMMsg_0067                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0067, _MrmMsg_0067)
#define _MrmMMsg_0068                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0068, _MrmMsg_0068)
#define _MrmMMsg_0069                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0069, _MrmMsg_0069)
#define _MrmMMsg_0070                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0070, _MrmMsg_0070)
#define _MrmMMsg_0071                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0071, _MrmMsg_0071)
#define _MrmMMsg_0072                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0072, _MrmMsg_0072)
#define _MrmMMsg_0073                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0073, _MrmMsg_0073)
#define _MrmMMsg_0074                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0074, _MrmMsg_0074)
#define _MrmMMsg_0075                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0075, _MrmMsg_0075)
#define _MrmMMsg_0076                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0076, _MrmMsg_0076)
#define _MrmMMsg_0077                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0077, _MrmMsg_0077)
#define _MrmMMsg_0078                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0078, _MrmMsg_0078)
#define _MrmMMsg_0079                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0079, _MrmMsg_0079)
#define _MrmMMsg_0080                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0080, _MrmMsg_0080)
#define _MrmMMsg_0081                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0081, _MrmMsg_0081)
#define _MrmMMsg_0082                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0082, _MrmMsg_0082)
#define _MrmMMsg_0083                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0083, _MrmMsg_0083)
#define _MrmMMsg_0084                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0084, _MrmMsg_0084)
#define _MrmMMsg_0085                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0085, _MrmMsg_0085)
#define _MrmMMsg_0086                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0086, _MrmMsg_0086)
#define _MrmMMsg_0087                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0087, _MrmMsg_0087)
#define _MrmMMsg_0088                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0088, _MrmMsg_0088)
#define _MrmMMsg_0089                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0089, _MrmMsg_0089)
#define _MrmMMsg_0090                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0090, _MrmMsg_0090)
#define _MrmMMsg_0091                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0091, _MrmMsg_0091)
#define _MrmMMsg_0092                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0092, _MrmMsg_0092)
#define _MrmMMsg_0093                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0093, _MrmMsg_0093)
#define _MrmMMsg_0094                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0094, _MrmMsg_0094)
#define _MrmMMsg_0095                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0095, _MrmMsg_0095)
#define _MrmMMsg_0096                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0096, _MrmMsg_0096)
#define _MrmMMsg_0097                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0097, _MrmMsg_0097)
#define _MrmMMsg_0098                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0098, _MrmMsg_0098)
#define _MrmMMsg_0099                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0099, _MrmMsg_0099)
#define _MrmMMsg_0100                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0100, _MrmMsg_0100)
#define _MrmMMsg_0101                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0101, _MrmMsg_0101)
#define _MrmMMsg_0102                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0102, _MrmMsg_0102)
#define _MrmMMsg_0103                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0103, _MrmMsg_0103)
#define _MrmMMsg_0104                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0104, _MrmMsg_0104)
#define _MrmMMsg_0105                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0105, _MrmMsg_0105)
#define _MrmMMsg_0106                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0106, _MrmMsg_0106)
#define _MrmMMsg_0107                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0107, _MrmMsg_0107)
#define _MrmMMsg_0108                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0108, _MrmMsg_0108)
#define _MrmMMsg_0109                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0109, _MrmMsg_0109)
#define _MrmMMsg_0110                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0110, _MrmMsg_0110)
#define _MrmMMsg_0111                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0111, _MrmMsg_0111)
#define _MrmMMsg_0112                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0112, _MrmMsg_0112)
#define _MrmMMsg_0113                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0113, _MrmMsg_0113)
#define _MrmMMsg_0114                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0114, _MrmMsg_0114)
#define _MrmMMsg_0115                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0115, _MrmMsg_0115)
#define _MrmMMsg_0116                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0116, _MrmMsg_0116)
#define _MrmMMsg_0117                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0117, _MrmMsg_0117)
#define _MrmMMsg_0118                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0118, _MrmMsg_0118)
#define _MrmMMsg_0119                _MrmCatgets(Mrm_catd, MS_Mrm, MSG__0119, _MrmMsg_0119)
